version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
